#FROM eclipse-temurin:11-jdk-alpine
FROM arm64v8/eclipse-temurin:11-jdk

EXPOSE 8282

RUN mkdir -p /opt/ucb-judge/logs/uj-users
VOLUME /opt/ucb-judge/logs/uj-users

VOLUME /tmp

ENV PORT="PORT"
ENV CONFIG_SERVER_URI="CONFIG_SERVER_URI"

ENV EUREKA_SERVER_URI="EUREKA_SERVER_URI"
ENV CONFIG_SERVER_PROFILE="CONFIG_SERVER_PROFILE"
ENV ZIPKIN_SERVER_URI="ZIPKIN_SERVER_URI"

ENV RABBITMQ_HOST="RABBITMQ_HOST"
ENV RABBITMQ_USERNAME="RABBITMQ_USERNAME"
ENV RABBITMQ_PASSWORD="RABBITMQ_PASSWORD"
ENV RABBITMQ_VIRTUAL_HOST="RABBITMQ_VIRTUAL_HOST"

ENV KEYCLOAK_SERVER_URI="KEYCLOAK_SERVER_URI"
ENV KEYCLOAK_CLIENT_SECRET="KEYCLOAK_CLIENT_SECRET"
ENV KEYCLOAK_REALM="KEYCLOAK_REALM"
ENV KEYCLOAK_CLIENT_ID="KEYCLOAK_CLIENT_ID"
ENV FRONTEND_KEYCLOAK_CLIENT_ID="FRONTEND_KEYCLOAK_CLIENT_ID"

ARG DEPENDENCY=target/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app

ENTRYPOINT ["java","-cp","app:app/lib/*","ucb.judge.ujusers.UjUsersApplicationKt"]