server:
    port: 8080

spring:
  application:
      name: uj-users
  zipkin:
    base-url: ${ZIPKIN_SERVER_URI:http://localhost:9411}

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8711/eureka/}

keycloak:
  auth-server-url: ${KEYCLOAK_SERVER_URI:http://localhost:8090}
  autodetect-bearer-only: true
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:SH6XfTUQkphfEQdfiAmML1bNkE0Gq615}
  realm: ${KEYCLOAK_REALM:ucb-judge}
  resource: ${KEYCLOAK_CLIENT_ID:backend}
  ssl-required: none
  use-resource-role-mappings: false
  security-constraints:
    - auth-roles:
        - common_user
      security-collections:
        - name: account-settings
          patterns:
            - /v1/api/users
          omitted-methods:
            - GET
            - POST
            - OPTIONS

