server:
  port: 8080

spring:
  application:
    name: uj-users
  zipkin:
    base-url: ${ZIPKIN_SERVER_URI:http://localhost:9411}
  rabbitmq:
    host: sparrow-01.rmq.cloudamqp.com
    port: 5672
    username: ${RABBITMQ_USERNAME:itggwiot}
    password: ${RABBITMQ_PASSWORD:FNAc7QotPFaC73UICw8YedtO6GVSspwD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:itggwiot}

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8711/eureka/}

keycloak:
  auth-server-url: ${KEYCLOAK_SERVER_URI:http://localhost:8090}
  autodetect-bearer-only: true
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:SH6XfTUQkphfEQdfiAmML1bNkE0Gq615}
  realm: ${KEYCLOAK_REALM:ucb-judge}
  resource: ${KEYCLOAK_CLIENT_ID:backend}
  ssl-required: none
  use-resource-role-mappings: false
  security-constraints:
    - auth-roles:
        - common_user
      security-collections:
        - name: account-settings
          patterns:
            - /api/v1/users/profile/*
          omitted-methods:
            - OPTIONS
    - auth-roles:
        - professor_user
      security-collections:
        - name: professor-settings
          patterns:
            - /api/v1/users
            - /api/v1/users/professor
            - /api/v1/users/group/*
          omitted-methods:
            - OPTIONS
