# Get Access Token
POST http://localhost:8090/realms/ucb-judge/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

response_type=code&grant_type=client_credentials&client_id=backend&client_secret=SH6XfTUQkphfEQdfiAmML1bNkE0Gq615

> {%
    client.global.set("auth-token", "Bearer " + response.body["access_token"]);
    client.log(client.global.get("auth-token"));
%}

### Get all users
GET http://localhost:8080/v1/api/users
### Get user by username
GET http://localhost:8080/v1/api/users/username/jdoes
### Get user by id
GET http://localhost:8080/v1/api/users/b3b63369-9b6f-4d32-af84-2e7df6a4a6cc
### Update user
PUT http://localhost:8080/v1/api/users/b3b63369-9b6f-4d32-af84-2e7df6a4a6cc
Content-Type: Application/json

{
    "email": "jdoe123@ucb.edu.bo",
    "firstName": "Juan",
    "lastName": "Doe"
}

### Update user's password
PUT http://localhost:8080/v1/api/users/b3b63369-9b6f-4d32-af84-2e7df6a4a6cc/password
Content-Type: Application/json

{
  "password": "13DagostoD1969@"
}

### Group related endpoints
#### Find users by group
GET http://localhost:8080/v1/api/users/group/professors

